#  Python 기반 이미지 사용
FROM python:3.11-slim

#  필요한 시스템 패키지 설치
RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 libsm6 libxext6 libxrender-dev \
    && rm -rf /var/lib/apt/lists/* && apt-get clean

#  작업 디렉터리 생성 및 이동
WORKDIR /app

#  requirements 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#  코드 및 가중치 복사
COPY . .

#  FastAPI 실행 명령어
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]


